services:
  frontend:
    container_name: 'frontend'
    build:
      context: ./frontend
    ports:
      - '5173:8080'
    depends_on:
      - backend

  backend:
    container_name: 'backend'
    build:
      context: ./backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
