INSERT INTO sismo (localidad, fecha, profundidad, magnitud) VALUES ('Panguipulli', '2024-08-30', 112, 3.1);
INSERT INTO sismo (localidad, fecha, profundidad, magnitud) VALUES ('Pomaire', '2024-10-09', 45, 3.7);
INSERT INTO sismo (localidad, fecha, profundidad, magnitud) VALUES ('Pichilemu', '2024-10-04', 20, 6.6);
INSERT INTO sismo (localidad, fecha, profundidad, magnitud) VALUES ('Valdivia', '2024-08-25', 100, 9.1);
INSERT INTO suscripcion (email, localidad, nombre) VALUES ('frichterc+g5@gmail.com', 'Pomaire', 'Felipe');
INSERT INTO suscripcion (email, localidad, nombre) VALUES ('frichterc+g5@gmail.com', 'Valdivia', 'Felipe');
INSERT INTO suscripcion (email, localidad, nombre, activo) VALUES ('frichterc+g5@gmail.com', 'Panguipulli', 'El Inactivo', false);
INSERT INTO localidad (nombre) VALUES ('Quillota');
INSERT INTO localidad (nombre) VALUES ('San Pedro de Atacama');
INSERT INTO localidad (nombre) VALUES ('San Antonio de los Cobres');
INSERT INTO localidad (nombre) VALUES ('Copiapó');
INSERT INTO localidad (nombre) VALUES ('Visviri');
INSERT INTO localidad (nombre) VALUES ('Pica');
INSERT INTO localidad (nombre) VALUES ('Mina Collahuasi');
INSERT INTO localidad (nombre) VALUES ('Socaire');
INSERT INTO localidad (nombre) VALUES ('Constitución');
INSERT INTO localidad (nombre) VALUES ('Calama');
